### PR TITLE
Added NeilSayok.py. Program to convert image to pattern.

### PR DESCRIPTION
**Pull request by NeilSayok**

### CODE REVIEW

**Review by aritraroy24 — APPROVED** [review]
🟥 @NeilSayok I'm merging the branch without the phfa26.exe file (deleting that), as I think you have unintentionally added that file. However, the most important thing is that you have sent a PR before starting of Hacktoberfest2021 resulting in no count towards Hacktoberfest 4 successful PR. According to Hacktoberfest rules, all the 4 PRs should be done between Oct 1-31. 

👨‍💻 Regarding the code, it is just awesome. Involving OpenCV and the outcome...just loved it, bro!!! Will love to get a successful PR during the Hacktoberfest🙌🙌🙌

**Comment by NeilSayok** [comment]
Thanks for the merge I will create more PRs before Hactober fest.

**Comment by NeilSayok** [comment]
Hi Aritra,

Can you please specify how to make a 2nd file in the Repo

NeilSayok.py already exists so how can I make another file with the same
name.

Thanks Sayok

**Comment by aritraroy24** [comment]
@NeilSayok Glad to know you want to do a PR again...Don't bother about the filename...give any name to the file and in the Contributors.md file keep all the details empty except the file name and the pattern screenshot path (as you have already given other details) like following - 
|    |     |     |     |  your filename  |  screenshot path  |     |     |

**Comment by NeilSayok** [comment]
thats awesome

**Pull request merged**
