### PR TITLE
Adding Pattern

### PR DESCRIPTION
**Pull request by Himanshu-Agg12**

### CODE REVIEW

**Comment by aritraroy24** [comment]
@Himanshu-Agg12 Make sure to fulfil all [the criteria](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#-eligibility-criteria-). I'll merge when all the criteria are fulfilled.

**Comment by Himanshu-Agg12** [comment]
Which condition is missing, can you please specify.

**Comment by aritraroy24** [comment]
@Himanshu-Agg12 following the maintainer is also one of the criteria😊😊😊

**Comment by Himanshu-Agg12** [comment]
I followed you bro, Thanks for merging. Sent from Mail for Windows From: Aritra RoySent: Thursday, September 30, 2021 10:24 AMTo: aritraroy24/HACKTOBERFEST2021_PATTERNCc: Himanshu Aggarwal; MentionSubject: Re: [aritraroy24/HACKTOBERFEST2021_PATTERN] Adding Pattern ***@***.*** following the maintainer is also one of the criteria😊😊😊—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aritraroy24** [comment]
@Himanshu-Agg12 thnx bro❤️

**Comment by Himanshu-Agg12** [comment]
Bro can you tell me why this PR is not counted on hacktober fest website, I had done something wrong ?Help me please as I am new to this field.I want to say that The total count is still 0. Sent from Mail for Windows From: Aritra RoySent: Thursday, September 30, 2021 12:02 PMTo: aritraroy24/HACKTOBERFEST2021_PATTERNCc: Himanshu Aggarwal; MentionSubject: Re: [aritraroy24/HACKTOBERFEST2021_PATTERN] Adding Pattern ***@***.*** thnx bro❤️—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aritraroy24** [comment]
@Himanshu-Agg12 Oh bro...I thought you know...**the Hacktoberfest has not started yet**... today is the last day of **preptember**...you have to send a successful PR in the month of October i.e. between Oct 1 and Oct 31...however you can send multiple PR to any repo...so most welcome if you want to send more PRs in this repo...I have discussed with @NeilSayok  in another PR made by him what you have to do if you want to send multiple PRs in this repo...please check that thread if you want to send multiple PRs... and also keep in mind that the time is maintained in Hacktoberfest is basically based on PST timezone...

**Comment by Himanshu-Agg12** [comment]
Ohkay bro, Thanks for the guidance Sent from Mail for Windows From: Aritra RoySent: Thursday, September 30, 2021 12:21 PMTo: aritraroy24/HACKTOBERFEST2021_PATTERNCc: Himanshu Aggarwal; MentionSubject: Re: [aritraroy24/HACKTOBERFEST2021_PATTERN] Adding Pattern ***@***.*** Oh bro...I thought you know...the Hacktoberfest has not started yet... today is the last day of preptember...you have to send a successful PR in the month of October i.e. between Oct 1 and Oct 31...however you can send multiple PR to any repo...so most welcome if you want to send more PRs in this repo...I have discussed with @NeilSayok in another PR made by him what you have to do if you want to send multiple PRs in this repo...please check that thread if you want to send multiple PRs... and also keep in mind that the time is maintained in Hacktoberfest is basically based on PST timezone...—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
