### PR TITLE
I have added a pattern in repository in C++ language

### PR DESCRIPTION
**Pull request by Shubham56-droid**
thanks for accepting the PR

### CODE REVIEW

**Comment by aritraroy24** [comment]
@Shubham56-droid plz update the Contributors.md file and let me know...after that I'll merge

**Comment by aritraroy24** [comment]
@Shubham56-droid I'm closing the PR as it is not fulfilling the requirement...you can send a PR again after maintaining [all the steps](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#just-7-simple-steps-to-earn-your-t-shirt-for-hacktoberfest-2021-) and [eligibility criteria](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#-eligibility-criteria-) for a valid PR...

**Comment by Shubham56-droid** [comment]
ok, i will again send the pull request by updating the contribution.md

**Comment by aritraroy24** [comment]
@Shubham56-droid I have closed this PR....send a new one with all changes, not only Contribution.md

**Comment by Shubham56-droid** [comment]
Ok I will send all of the updated file

**Pull request closed without merging**
