### PR TITLE
Add upside down triangle

### PR DESCRIPTION
**Pull request by Dulyaaa**

### CODE REVIEW

**Comment by aritraroy24** [comment]
@Dulyaaa hey...give your photo in the Photos section, not the octocat one😅😅😅...modify that and I'll merge that...and don't forget to fetch before making any changes

**Comment by Dulyaaa** [comment]
> @Dulyaaa hey...give your photo in the Photos section, not the octocat one😅😅😅...modify that and I'll merge that...and don't forget to fetch before making any changes

@aritraroy24 Merged the code and open a new pull request  in #194

**Comment by Dulyaaa** [comment]
I think this branch is ok now. Then I will close #194 PR.

**Comment by Dulyaaa** [comment]
> > @aritraroy24 Hey..!! You keep me resolving conflicts😅. Plz be hurry and merge this😁
> 
> @Dulyaaa sorry dear!!! was a bit busy...I have merged

Heehee... thanks😊... 
I think you should add _hactoberfest-accepted_ label too...

**Pull request merged**
