### PR TITLE
Create atulnarayan16.py

### PR DESCRIPTION
**Pull request by atulnarayan16**
Adding Pattern

### CODE REVIEW

**Comment by aritraroy24** [comment]
@atulnarayan16 please follow all the steps mentioned in the documentary...otherwise, your PR will be marked as invalid...though as you have sent the PR before starting Hacktoberfest2021, it'll not be counted as a valid PR in hacktoberfest

**Comment by atulnarayan16** [comment]
Sorry. I am a first timer, I did not know how to do all the steps properly.
If you could tell me or guide me which steps I did not follow , I would be
grateful.

**Comment by aritraroy24** [comment]
@atulnarayan16 Please read [all the steps](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#just-7-simple-steps-to-earn-your-t-shirt-for-hacktoberfest-2021-) and [eligibility criteria](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#-eligibility-criteria-)

**Comment by aritraroy24** [comment]
@atulnarayan16 I'm closing the PR as it is not fulfilling the requirement...you can send a PR again after maintaining [all the steps](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#just-7-simple-steps-to-earn-your-t-shirt-for-hacktoberfest-2021-) and [eligibility criteria](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN#-eligibility-criteria-) for a valid PR...

**Pull request closed without merging**
